[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C86890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C86F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C87850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C819D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C82010>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E38F1690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d357758b8b0742e0002769c77dcf0ba4