[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DE2610>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DE2E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DE36D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DE5850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DE5E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000023E09DBF450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/5642cfdf489b6202323b01c67a6d5b57