[33mWARNING [0m selenium.webdriver.common.selenium_manager:selenium_manager.py:149 The chromedriver version (120.0.6099.109) detected in PATH at G:\Django\core\VEG_REC\chromedriver.exe might not be compatible with the detected chrome version (121.0.6167.140); currently, chromedriver 121.0.6167.85 is recommended for chrome 121.*, so it is advised to delete the driver in PATH and retry
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255889A6190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f192fa7314f6d8b5845df0f9da5ab9f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255889A6B50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f192fa7314f6d8b5845df0f9da5ab9f
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000255889A7450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/3f192fa7314f6d8b5845df0f9da5ab9f