[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C6D290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4449e12669e79c71420df5b6f6728335
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C6D7D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4449e12669e79c71420df5b6f6728335
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000248E3C6DF10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/4449e12669e79c71420df5b6f6728335