[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FDE290>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FDEA50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FDF310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FE1550>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FE1B90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FC3310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/1048e6fadd10ecedb2c5819576f41b4e